//BASE URL
export const BASE_URL = "https://api.hatchways.io"

//STUDENTS
export const ADD_TAG = "ADD_TAG"
export const CLEAR_NAME_FILTER = "CLEAR_NAME_FILTER"
export const CLEAR_TAG_FILTER = "CLEAR_TAG_FILTER"
export const STUDENT_ERROR = "STUDENT_ERROR"
export const FILTER_STUDENTS_BY_NAME = "FILTER_STUDENTS_BY_NAME"
export const FILTER_STUDENTS_BY_TAG = "FILTER_STUDENTS_BY_TAG"
export const GET_STUDENTS = "GET_STUDENTS"


